# Generated by Django 3.0.5 on 2020-04-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='second_category',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='third_category',
            old_name='Name',
            new_name='name',
        ),
    ]
