# Generated by Django 3.0.5 on 2020-04-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIncident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('personalNumber', models.CharField(max_length=12)),
                ('time', models.DateField(default=None, null=True)),
                ('description', models.TextField(max_length=500)),
                ('action', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
