# Generated by Django 3.0.5 on 2020-04-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20200415_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 17, 20, 52, 990593)),
        ),
    ]
