# Generated by Django 3.0.5 on 2020-04-19 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_auto_20200416_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='patient_firstname',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='incident',
            name='patient_lastname',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='incident',
            name='patient_sex',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='suggestion',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='action',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 13, 36, 8, 39991)),
        ),
        migrations.AlterField(
            model_name='incident',
            name='personal_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
