# Generated by Django 3.0.5 on 2020-04-21 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_auto_20200419_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 13, 5, 15, 990957)),
        ),
    ]
