# Generated by Django 3.0.5 on 2020-04-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20200422_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('Risk', 'Risk'), ('Near miss', 'Near miss'), ('Adverse Event', 'Adverse Event')], default='Risk', max_length=20, null=True),
        ),
    ]
