# Generated by Django 3.0.5 on 2020-04-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_auto_20200426_1044'),
        ('incidents', '0006_auto_20200421_1305'),
    ]

    operations = [
    ]
