# Generated by Django 3.0.5 on 2020-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0010_merge_20200428_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.CharField(max_length=12),
        ),
    ]
